# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
#
# Node2: Prometheus + Grafana (Observability Stack)
# This provides metrics storage and visualization.

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

networks:
  default:
    name: opentelemetry-demo
    driver: bridge

services:
  # Prometheus
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.listen-address=0.0.0.0:9090
    volumes:
      - ./src/prometheus/prometheus-config-cloudlab.yaml:/etc/prometheus/prometheus-config.yaml
      - prometheus-data:/prometheus
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    ports:
      - "9090:9090"
    logging: *logging

  # Grafana
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
      - "GF_SERVER_HTTP_ADDR=0.0.0.0"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
    volumes:
      - ./src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./src/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    logging: *logging

volumes:
  prometheus-data:
  grafana-data:
