# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]
#

exporters:
  file/traces:
    path: /traces/traces.json
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 100

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlp, debug, file/traces]
